spring:
  datasource:
    url: jdbc:mysql://localhost:3306/staff_manager?characterEncoding=UTF-8&serverTimezone=GMT%2B8&useSSL=false&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
  profiles:
    active: dev
  application:
    name: staff
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  servlet:
    multipart:
      max-file-size: 1024MB
      max-request-size: 1024MB
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

server:
  port: 9181
  tomcat:
    uri-encoding: UTF-8

mybatis-plus:
  mapper-locations: classpath:com/rabbiter/staff/mapper/xml/*.xml
